---
- name: Add NTP config
  hosts: "{{ targets }}"
  gather_facts: no

  tasks: 
    - name: print ssh key
      debug:
        msg: "{{ ANSIBLE_NET_SSH_KEYFILE }}"
    - name: set NTP config on Juniper
      junos_config:
        ssh_private_key_file: '{{ lookup(env, "ANSIBLE_NET_SSH_KEYFILE") }}'
        lines:
          - set system ntp server 196.4.160.4
          - set system ntp peer 196.4.160.4
          - set routing-options static route 196.4.160.4/32 next-hop 10.84.0.1
