---
- name: Load and commit configuration data on a device running Junos OS
  hosts: vMX1
  connection: local
  gather_facts: no

  tasks: 
    - name: Checking NETCONF connectivity
      wait_for: 
        host: "{{ inventory_hostname }}" 
        port: 830  
        timeout: 5
