---
- name: Run Junos Command
  hosts: "{{ targets }}"
  gather_facts: no

  tasks: 
    - name: Run command
      junos_command:
        commands: "{{ command }}"
      register: output
    - name: show output
      debug:
        var: output
        verbosity: 2
