---
- name: Add JTI Resource
  hosts: "{{ targets }}"
  gather_facts: no

  vars:
    commands: []

  tasks: 
    - name: showing the mchoice var
      debug:
        msg: "{{ interfaces }}"
    - name: Populate list of commands
      set_fact:
        commands: "{{ commands }} + ['set groups CORE_INTERNAL interfaces {{item}} unit 0 family mpls']"
      with_items: "{{ interfaces }}"
    - name: showing the commands
      debug:
        msg: "{{ commands }}"
    - name: load configure lines into device
      junos_config:
        lines: "{{ commands }}"
