---
- name: Get device facts and configuration
  hosts: vMX1
  connection: local
  gather_facts: no

  vars:
    query: 'ansible_facts.ansible_net_config.configuration.services.analytics."export-profile"'

  tasks:
    - name: Initializing an empty variable to hold server names
      set_fact:
        server_list: ""
    - name: Fetch latest config from Device
      junos_facts:
        gather_subset: config
        config_format: "json"
      register: facts
    - name: Getting relevant configured values
      set_fact:
        server_list: "{{server_list}}{{item.name}}\n"
      loop : "{{ facts | json_query(query) }}"


- name: Updating AWX
  hosts: vMX1
  connection: local
  become: yes
  gather_facts: no
  vars:   
    admin_password: "password"
    admin_username: "admin"
    tower_url: "http://10.84.9.5"
  tasks:  
  - name: Update multiple choice options for export list in json
    json_patch:
      src: "/var/lib/awx/projects/jti_survey.json"
      operations:
        - op: replace
          path: "/spec/1/choices"
          value: "{{server_list}}"
  - name: Update multiple choice options for server list in json
    json_patch:
      src: "/var/lib/awx/projects/jti_survey.json"
      operations:
        - op: replace
          path: "/spec/2/choices"
          value: "{{server_list}}"
  - name: Create/Update JTI Template
    tower_job_template:
      name: "Add JTI Resource"
      job_type: "run"
      inventory: "vMX on EVE"
      project: "Juniper Demo"
      playbook: "add-jti.yml"
      credential: "Juniper Demo"
      survey_enabled: true
      survey_spec: "{{ lookup('file', 'jti_survey.json') }}"
      ask_limit: True
      tower_username: "{{admin_username}}"
      tower_password: "{{admin_password}}"
      tower_host: "{{tower_url}}"
      validate_certs: no
