- hosts: localhost
  vars:
   host: "{{target}}"
   username: "{{fortiapi_user}}"
   password: "{{fortiapi_password}}"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure interfaces.
    fortios_system_interface:
      host: "{{target}}"
      username: "{{fortiapi_user}}"
      password: "{{fortiapi_password}}"
      vdom: "root"
      https: "False"
      system_interface:
        name: "{{port}}"
        alias: "{{alias}}"
        state: "present"
