- hosts: localhost
  vars:
   host: "{{target}}"
   username: "admin"
   password: "XonXoff"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure interfaces.
    fortios_system_interface:
      host: "{{target}}"
      username: "admin"
      password: "XonXoff"
      vdom: "root"
      https: "False"
      state: "present"
      system_interface:
        name: "{{port}}"
        alias: "{{alias}}"
