- hosts: localhost
  vars:
   host: "{{target}}"
   username: "awx"
   password: "Hsmy6rm7yrhg86Q4w0hsHmn6N6hQ1z"
   vdom: "root"
   ssl_verify: "False"
  tasks:
  - name: Configure interfaces.
    fortios_system_interface:
      host: "{{target}}"
      username: "awx"
      password: "Hsmy6rm7yrhg86Q4w0hsHmn6N6hQ1z"
      vdom: "root"
      https: "False"
      system_interface:
        name: "{{port}}"
        alias: "{{alias}}"
        state: "present"
