---
- name: Update DHCP Server config
  hosts: NX-OS

  tasks:
    - name: Update DHCP Server config
      blockinfile:
        path: /etc/dhcp/dhcpd.conf
        block: |
          host {{ vendor_id }} {
            hardware ethernet {{mac}};
            option tftp-server-name "100.64.69.1";
            option host-name "{{ hostname }}";
            option NEW_OP.transfer-mode "ftp";
            option NEW_OP.config-file-name "/dist/config/{{ hostname }}.config";
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostname }}"
      register: dhcp

    - name: Restart isc-dhcp-server 
      service: name=isc-dhcp-server state=restarted
      when: dhcp['changed']

    - name: deploy initial config
      template:
        src: templates/initial.j2
        dest: "/var/ftp/dist/config/{{ hostname }}.config"


- name: Updating AWX
  hosts: AWX
  connection: local
  become: yes
  gather_facts: no
  tasks:
  - name: Create host on AWX
    tower_host:
      name: "{{fxp0_address}}"
      inventory: "vMX on EVE"
      state: present
      variables:
        ansible_connection: netconf
        ansible_network_os: junos
        ansible_user: awx
  - name: Create group on AWX
    tower_group:
      name: "{{hostname}}"
      inventory: "vMX on EVE"
      state: present
  - name: Assign Host to Group
    command:
      "awx-cli host associate --host {{ fxp0_address|quote}} --group {{ hostname|quote }}"
