---
- name: Update DHCP Server config
  hosts: all

  blockinfile:
    path: /etc/dhcp/dhcpd.conf
    block: |
      host {{ vendor_id }} {
        hardware ethernet 50:07:00:01:00:00;
        option tftp-server-name "100.64.69.1";
        option host-name "vMX1";
        option NEW_OP.image-file-name "/dist/images/jinstall-ex-4200-13.2R1.1-domestic-signed.tgz";
        option NEW_OP.transfer-mode "ftp";
        option NEW_OP.config-file-name "/dist/config/jn-switch35.config";
      }
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostname }}"
