---
- name: Update DHCP Server config
  hosts: all

  tasks:
    - name: Update DHCP Server config
      blockinfile:
        path: /etc/dhcp/dhcpd.conf
        block: |
          host {{ vendor_id }} {
            hardware ethernet {{mac}};
            option tftp-server-name "100.64.69.1";
            option host-name "{{ hostname }}";
            option NEW_OP.transfer-mode "ftp";
            option NEW_OP.config-file-name "/dist/config/{{ hostname }}.config";
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostname }}"

    - name: Restart isc-dhcp-server 
      service: name=isc-dhcp-server state=restarted

    - name: deploy initial config
      template:
        src: templates/initial.j2
        dest: "/var/ftp/dist/config/{{ hostname }}.config"


- name: Updating AWX
  hosts: all
  connection: local
  gather_facts: no
  vars:
    admin_password: "password"
    admin_username: "admin"
    tower_url: "http://10.84.9.5"
  tasks:
  - name: Create device on AWX
    tower_host:
      name: "{{hostname}}"
      inventory: "vMX on EVE"
      state: present
      variables:
        ansible_host: "{{hostname}}"
        inventory_hostname: "{{hostname}}"
